/**
 * 都道府県
 */
export enum Prefecture {
  ONLINE = 'online',
  HOKKAIDO = 'hokkaido',
  AOMORI = 'aomori',
  IWATE = 'iwate',
  MIYAGI = 'miyagi',
  AKITA = 'akita',
  YAMAGATA = 'yamagata',
  FUKUSHIMA = 'fukushima',
  IBARAKI = 'ibaraki',
  TOCHIGI = 'tochigi',
  GUNMA = 'gunma',
  SAITAMA = 'saitama',
  CHIBA = 'chiba',
  TOKYO = 'tokyo',
  KANAGAWA = 'kanagawa',
  YAMANASHI = 'yamanashi',
  NAGANO = 'nagano',
  NIIGATA = 'niigata',
  TOYAMA = 'toyama',
  ISHIKAWA = 'ishikawa',
  FUKUI = 'fukui',
  GIFU = 'gifu',
  SHIZUOKA = 'shizuoka',
  AICHI = 'aichi',
  MIE = 'mie',
  SHIGA = 'shiga',
  KYOTO = 'kyoto',
  OSAKA = 'osaka',
  HYOGO = 'hyogo',
  NARA = 'nara',
  WAKAYAMA = 'wakayama',
  TOTTORI = 'tottori',
  SHIMANE = 'shimane',
  OKAYAMA = 'okayama',
  HIROSHIMA = 'hiroshima',
  YAMAGUCHI = 'yamaguchi',
  TOKUSHIMA = 'tokushima',
  KAGAWA = 'kagawa',
  EHIME = 'ehime',
  KOCHI = 'kochi',
  FUKUOKA = 'fukuoka',
  SAGA = 'saga',
  NAGASAKI = 'nagasaki',
  KUMAMOTO = 'kumamoto',
  OITA = 'oita',
  MIYAZAKI = 'miyazaki',
  KAGOSHIMA = 'kagoshima',
  OKINAWA = 'okinawa',
}
